[2024-09-12T11:47:16.134+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: shopeefood_crawl_and_report.process_report manual__2024-09-12T11:39:14.687270+00:00 [queued]>
[2024-09-12T11:47:16.143+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: shopeefood_crawl_and_report.process_report manual__2024-09-12T11:39:14.687270+00:00 [queued]>
[2024-09-12T11:47:16.144+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2024-09-12T11:47:16.159+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): process_report> on 2024-09-12 11:39:14.687270+00:00
[2024-09-12T11:47:16.164+0000] {standard_task_runner.py:60} INFO - Started process 3685 to run task
[2024-09-12T11:47:16.167+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'shopeefood_crawl_and_report', 'process_report', 'manual__2024-09-12T11:39:14.687270+00:00', '--job-id', '25', '--raw', '--subdir', 'DAGS_FOLDER/main_dag.py', '--cfg-path', '/tmp/tmpkhc_e3o5']
[2024-09-12T11:47:16.170+0000] {standard_task_runner.py:88} INFO - Job 25: Subtask process_report
[2024-09-12T11:47:16.218+0000] {task_command.py:423} INFO - Running <TaskInstance: shopeefood_crawl_and_report.process_report manual__2024-09-12T11:39:14.687270+00:00 [running]> on host bc7cb9c82b76
[2024-09-12T11:47:16.424+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='shopeefood_crawl_and_report' AIRFLOW_CTX_TASK_ID='process_report' AIRFLOW_CTX_EXECUTION_DATE='2024-09-12T11:39:14.687270+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-12T11:39:14.687270+00:00'
[2024-09-12T11:47:16.460+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/report/process_data.py", line 55, in process_get_report
    df[['min_cost', 'max_cost']] = df['cost_res'].apply(lambda x: pd.Series(parse_cost_range(x)))
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/series.py", line 4630, in apply
    return SeriesApply(self, func, convert_dtype, args, kwargs).apply()
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/apply.py", line 1025, in apply
    return self.apply_standard()
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/apply.py", line 1076, in apply_standard
    mapped = lib.map_infer(
  File "pandas/_libs/lib.pyx", line 2834, in pandas._libs.lib.map_infer
  File "/opt/airflow/dags/report/process_data.py", line 55, in <lambda>
    df[['min_cost', 'max_cost']] = df['cost_res'].apply(lambda x: pd.Series(parse_cost_range(x)))
  File "/opt/airflow/dags/report/process_data.py", line 47, in parse_cost_range
    parts = cost_range.split(' - ')
AttributeError: 'float' object has no attribute 'split'
[2024-09-12T11:47:16.479+0000] {taskinstance.py:1149} INFO - Marking task as UP_FOR_RETRY. dag_id=shopeefood_crawl_and_report, task_id=process_report, execution_date=20240912T113914, start_date=20240912T114716, end_date=20240912T114716
[2024-09-12T11:47:16.491+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 25 for task process_report ('float' object has no attribute 'split'; 3685)
[2024-09-12T11:47:16.502+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-09-12T11:47:16.524+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
