[2024-09-12T14:35:26.601+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: shopeefood_crawl_and_report.crawl_list_restaurant manual__2024-09-12T14:35:24.498758+00:00 [queued]>
[2024-09-12T14:35:26.616+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: shopeefood_crawl_and_report.crawl_list_restaurant manual__2024-09-12T14:35:24.498758+00:00 [queued]>
[2024-09-12T14:35:26.618+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2024-09-12T14:35:26.639+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): crawl_list_restaurant> on 2024-09-12 14:35:24.498758+00:00
[2024-09-12T14:35:26.648+0000] {standard_task_runner.py:60} INFO - Started process 15627 to run task
[2024-09-12T14:35:26.653+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'shopeefood_crawl_and_report', 'crawl_list_restaurant', 'manual__2024-09-12T14:35:24.498758+00:00', '--job-id', '99', '--raw', '--subdir', 'DAGS_FOLDER/main_dag.py', '--cfg-path', '/tmp/tmp5hjz0gpf']
[2024-09-12T14:35:26.656+0000] {standard_task_runner.py:88} INFO - Job 99: Subtask crawl_list_restaurant
[2024-09-12T14:35:26.786+0000] {task_command.py:423} INFO - Running <TaskInstance: shopeefood_crawl_and_report.crawl_list_restaurant manual__2024-09-12T14:35:24.498758+00:00 [running]> on host bc7cb9c82b76
[2024-09-12T14:35:27.487+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='shopeefood_crawl_and_report' AIRFLOW_CTX_TASK_ID='crawl_list_restaurant' AIRFLOW_CTX_EXECUTION_DATE='2024-09-12T14:35:24.498758+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-12T14:35:24.498758+00:00'
[2024-09-12T14:35:54.883+0000] {logging_mixin.py:188} INFO - Lỗi khi chờ đợi sản phẩm: Message:
[2024-09-12T14:35:54.935+0000] {logging_mixin.py:188} INFO - Lỗi khi chuyển trang hoặc crawl trang: Message: no such element: Unable to locate element: {"method":"css selector","selector":"a[href="#"] .icon-paging-next"}
  (Session info: headless chrome=117.0.5938.132); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
#0 0x557da071f6b3 <unknown>
#1 0x557da03f51e7 <unknown>
#2 0x557da043c566 <unknown>
#3 0x557da043c651 <unknown>
#4 0x557da0479a74 <unknown>
#5 0x557da045e0ed <unknown>
#6 0x557da0477322 <unknown>
#7 0x557da045de93 <unknown>
#8 0x557da0430934 <unknown>
#9 0x557da043171e <unknown>
#10 0x557da06e4cb8 <unknown>
#11 0x557da06e8bf0 <unknown>
#12 0x557da06f319c <unknown>
#13 0x557da06e9808 <unknown>
#14 0x557da06b627f <unknown>
#15 0x557da070de88 <unknown>
#16 0x557da070e059 <unknown>
#17 0x557da071e843 <unknown>
#18 0x7f65f9726609 start_thread
[2024-09-12T14:35:55.012+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/crawler/crawl_list_restaurant.py", line 57, in crawl_list_restaurant
    df.columns=['name', 'promotion', 'store_url']
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/generic.py", line 6002, in __setattr__
    return object.__setattr__(self, name, value)
  File "pandas/_libs/properties.pyx", line 69, in pandas._libs.properties.AxisProperty.__set__
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/generic.py", line 730, in _set_axis
    self._mgr.set_axis(axis, labels)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/internals/managers.py", line 225, in set_axis
    self._validate_set_axis(axis, new_labels)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/internals/base.py", line 70, in _validate_set_axis
    raise ValueError(
ValueError: Length mismatch: Expected axis has 0 elements, new values have 3 elements
[2024-09-12T14:35:55.040+0000] {taskinstance.py:1149} INFO - Marking task as UP_FOR_RETRY. dag_id=shopeefood_crawl_and_report, task_id=crawl_list_restaurant, execution_date=20240912T143524, start_date=20240912T143526, end_date=20240912T143555
[2024-09-12T14:35:55.060+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 99 for task crawl_list_restaurant (Length mismatch: Expected axis has 0 elements, new values have 3 elements; 15627)
[2024-09-12T14:35:55.087+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-09-12T14:35:55.120+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
