[2024-09-12T12:55:28.782+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: shopeefood_crawl_and_report.crawl_list_restaurant manual__2024-09-12T12:49:28.334367+00:00 [queued]>
[2024-09-12T12:55:28.802+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: shopeefood_crawl_and_report.crawl_list_restaurant manual__2024-09-12T12:49:28.334367+00:00 [queued]>
[2024-09-12T12:55:28.803+0000] {taskinstance.py:2193} INFO - Starting attempt 5 of 6
[2024-09-12T12:55:28.832+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): crawl_list_restaurant> on 2024-09-12 12:49:28.334367+00:00
[2024-09-12T12:55:28.841+0000] {standard_task_runner.py:60} INFO - Started process 8590 to run task
[2024-09-12T12:55:28.847+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'shopeefood_crawl_and_report', 'crawl_list_restaurant', 'manual__2024-09-12T12:49:28.334367+00:00', '--job-id', '68', '--raw', '--subdir', 'DAGS_FOLDER/main_dag.py', '--cfg-path', '/tmp/tmpn3opje8o']
[2024-09-12T12:55:28.851+0000] {standard_task_runner.py:88} INFO - Job 68: Subtask crawl_list_restaurant
[2024-09-12T12:55:28.937+0000] {task_command.py:423} INFO - Running <TaskInstance: shopeefood_crawl_and_report.crawl_list_restaurant manual__2024-09-12T12:49:28.334367+00:00 [running]> on host bc7cb9c82b76
[2024-09-12T12:55:29.325+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='shopeefood_crawl_and_report' AIRFLOW_CTX_TASK_ID='crawl_list_restaurant' AIRFLOW_CTX_EXECUTION_DATE='2024-09-12T12:49:28.334367+00:00' AIRFLOW_CTX_TRY_NUMBER='5' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-12T12:49:28.334367+00:00'
[2024-09-12T12:58:29.864+0000] {local_task_job_runner.py:302} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2024-09-12T12:58:29.867+0000] {process_utils.py:131} INFO - Sending 15 to group 8590. PIDs of all processes in the group: [8590]
[2024-09-12T12:58:29.868+0000] {process_utils.py:86} INFO - Sending the signal 15 to group 8590
[2024-09-12T12:58:29.869+0000] {taskinstance.py:2483} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-09-12T12:58:29.921+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=8590, status='terminated', exitcode=0, started='12:55:27') (8590) terminated with exit code 0
